export var API_DOMAIN ='http://localhost:8080'
export var API_URL = ``

//login action names
export const LOGIN_LOADING = "LOGIN_LOADING"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"

//register action names
export const REGISTER_LOADING = "REGISTER_LOADING"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILED = "REGISTER_FAILED"


//website creation
export const CREATE_WEBSITE_LOADING = "CREATE_WEBSITE_LOADING"
export const CREATE_WEBSITE_SUCCESS = "CREATE_WEBSITE_SUCCESS"
export const CREATE_WEBSITE_FAILED = "CREATE_WEBSITE_FAILED"

//websites 
export const UPDATE_WEBSITE_LOADING = "UPDATE_WEBSITE_LOADING"
export const UPDATE_WEBSITE_SUCCESS = "UPDATE_WEBSITE_SUCCESS"
export const UPDATE_WEBSITE_FAILED = "UPDATE_WEBSITE_FAILED"

//draft creation
export const CREATE_DRAFT_LOADING ="CREATE_DRAFT_LOADING"
export const CREATE_DRAFT_SUCCESS ="CREATE_DRAFT_SUCCESS"
export const CREATE_DRAFT_FAILED = "CREATE_DRAFT_FAILED"

//drafts
export const GET_DRFT_LOADING = "GET_DRFT_LOADING"
export const GET_DRFT_SUCCESS = "GET_DRFT_SUCCESS"
export const GET_DRFT_FAILED = "GET_DRFT_FAILED"

//file uploading
export const UPLOAD_FILE_LOADING = "UPLOAD_FILE_LOADING"
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS"
export const UPLOAD_FILE_FAILED  = "UPLOAD_FILE_FAILED"

//websites
export const GET_WEBSITES_LOADING = "GET_WEBSITES_LOADING"
export const GET_WEBSITES_SUCCESS = "GET_WEBSITES_SUCCESS"
export const GET_WEBSITES_FAILED = "GET_WEBSITES_FAILED"

export const GET_WEBSITE_LOADING = "GET_WEBSITE_LOADING"
export const GET_WEBSITE_SUCCESS = "GET_WEBSITE_SUCCESS"
export const GET_WEBSITE_FAILED = "GET_WEBSITE_FAILED"

export const CLEAR_UPDATE_DATA = "CLEAR_UPDATE_DATA"

//password change
export const CHANGE_PASSWORD_LOADING = "CHANGE_PASSWORD_LOADING"
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS"
export const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED"


export const SET_IMAGE_FILES = "SET_IMAGE_FILES";
export const CLEAR_IMAGE_FILES = "CLEAR_IMAGE_FILES";
export const SET_COVER = "SET_COVER";
export const CLEAR_COVER = "CLEAR_COVER";


//cover uploading
export const UPLOAD_COVER_LOADING = "UPLOAD_COVER_LOADING"
export const UPLOAD_COVER_SUCCESS = "UPLOAD_COVER_SUCCESS"
export const UPLOAD_COVER_FAILED  = "UPLOAD_COVER_FAILED"
